/**
 *
 * $Id$
 */
package org.mdmi.validation;

import org.eclipse.emf.common.util.EList;
import org.mdmi.Node;

/**
 * A sample validator interface for {@link org.mdmi.Bag}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BagValidator {
	boolean validate();

	boolean validateIsUnique(boolean value);

	boolean validateIsOrdered(boolean value);

	boolean validateNodes(EList<Node> value);
}
