/**
 *
 * $Id$
 */
package org.mdmi.validation;

import org.eclipse.emf.common.util.EList;
import org.mdmi.MDMIBusinessElementReference;
import org.mdmi.MessageGroup;

/**
 * A sample validator interface for {@link org.mdmi.MDMIDomainDictionaryReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MDMIDomainDictionaryReferenceValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateDescription(String value);

	boolean validateBusinessElements(EList<MDMIBusinessElementReference> value);

	boolean validateReference(String value);

	boolean validateGroup(MessageGroup value);
}
