/**
 *
 * $Id$
 */
package org.mdmi.validation;

import org.eclipse.emf.common.util.EList;
import org.mdmi.MDMIBusinessElementRule;
import org.mdmi.MDMIDatatype;
import org.mdmi.MDMIDomainDictionaryReference;

/**
 * A sample validator interface for {@link org.mdmi.MDMIBusinessElementReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MDMIBusinessElementReferenceValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateDescription(String value);

	boolean validateReference(String value);

	boolean validateUniqueIdentifier(String value);

	boolean validateBusinessRules(EList<MDMIBusinessElementRule> value);

	boolean validateDomainDictionaryReference(MDMIDomainDictionaryReference value);

	boolean validateReferenceDatatype(MDMIDatatype value);

	boolean validateEnumValueSetField(String value);

	boolean validateEnumValueField(String value);

	boolean validateEnumValueDescrField(String value);

	boolean validateEnumValueSet(String value);

	boolean validateReadonly(Boolean value);
}
