/**
 *
 * $Id$
 */
package org.mdmi.validation;

import org.mdmi.MessageModel;
import org.mdmi.Node;
import org.mdmi.SemanticElementSet;

/**
 * A sample validator interface for {@link org.mdmi.MessageSyntaxModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MessageSyntaxModelValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateModel(MessageModel value);

	boolean validateRoot(Node value);

	boolean validateElementSet(SemanticElementSet value);

	boolean validateDescription(String value);
}
