/**
 *
 * $Id$
 */
package org.mdmi.validation;

import org.eclipse.emf.common.util.EList;
import org.mdmi.DataRule;
import org.mdmi.MDMIDatatype;
import org.mdmi.MDMIDomainDictionaryReference;
import org.mdmi.MessageModel;

/**
 * A sample validator interface for {@link org.mdmi.MessageGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MessageGroupValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateDataRules(EList<DataRule> value);

	boolean validateDescription(String value);

	boolean validateDefaultLocationExprLang(String value);

	boolean validateDefaultConstraintExprLang(String value);

	boolean validateDefaultRuleExprLang(String value);

	boolean validateDefaultFormatExpressionLanguage(String value);

	boolean validateDefaultOrderingExpressionLanguage(String value);

	boolean validateModels(EList<MessageModel> value);

	boolean validateDomainDictionary(MDMIDomainDictionaryReference value);

	boolean validateDefaultMDMIExpresionLanguage(String value);

	boolean validateRules(EList<DataRule> value);

	boolean validateDatatypes(EList<MDMIDatatype> value);
}
