/**
 *
 * $Id$
 */
package org.mdmi.validation;

import org.mdmi.MessageSyntaxModel;
import org.mdmi.SemanticElement;

/**
 * A sample validator interface for {@link org.mdmi.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateDescription(String value);

	boolean validateMinOccurs(int value);

	boolean validateMaxOccurs(int value);

	boolean validateLocation(String value);

	boolean validateLocationExpressionLanguage(String value);

	boolean validateSyntaxModel(MessageSyntaxModel value);

	boolean validateSemanticElement(SemanticElement value);

	boolean validateFieldName(String value);

	boolean validateIsSyntacticField(boolean value);
}
