/**
 *
 * $Id$
 */
package org.mdmi.validation;

import org.eclipse.emf.common.util.EList;
import org.mdmi.MessageModel;
import org.mdmi.MessageSyntaxModel;
import org.mdmi.SemanticElement;
import org.mdmi.SimpleMessageComposite;

/**
 * A sample validator interface for {@link org.mdmi.SemanticElementSet}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SemanticElementSetValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateDescription(String value);

	boolean validateMessageModelName(String value);

	boolean validateSyntaxModel(MessageSyntaxModel value);

	boolean validateModel(MessageModel value);

	boolean validateSemanticElements(EList<SemanticElement> value);

	boolean validateComposite(EList<SimpleMessageComposite> value);
}
