/**
 *
 * $Id$
 */
package org.mdmi.validation;

import org.mdmi.SemanticElement;

/**
 * A sample validator interface for {@link org.mdmi.SemanticElementRelationship}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SemanticElementRelationshipValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateDescription(String value);

	boolean validateRule(String value);

	boolean validateRuleExpressionLanguage(String value);

	boolean validateContext(SemanticElement value);

	boolean validateMinOccurs(int value);

	boolean validateMaxOccurs(int value);

	boolean validateSourceIsInstance(boolean value);

	boolean validateTargetIsInstance(boolean value);
}
